# Site settings
title: PsychAD
name: "PsychAD Consortium"
description: >-
  The PsychAD Consortium builds population-scale, single-cell models of the
  human brain to uncover the molecular mechanisms behind neuropsychiatric
  symptoms in Alzheimer's disease, related dementias, and serious mental illness.
url: "https://psych-ad.org"

# Theme engine (customized via assets/css/main.scss)
minimal_mistakes_skin: "default"

# Branding
logo: "/assets/images/PsychAD_logo_notext.png"
masthead_title: "PsychAD"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone: EDT

include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/center-for-disease-neurogenomics/"
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/CDNeurogenomics"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DiseaseNeuroGenomics"
    - label: "CDN"
      icon: "fas fa-fw fa-link"
      url: "https://icahn.mssm.edu/research/neurogenomics"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      classes: wide
      author_profile: false
